services:
  discovery-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: arseniherasimovichinnowise/discovery-service
    ports:
      - '8761'
    networks:
      - backend-net
    environment:
      - SERVER_PORT=8761
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
networks:
  backend-net:
    external: true